2014-10-21 10:09:33,008 [9] ERROR LeaRun.DataAccess.DbHelper - 连接超时时间已到。在登录后阶段超过了此超时时间。连接可能在等待服务器完成登录过程并响应时超时；或者在尝试创建多个活动连接时超时。  尝试连接到此服务器时花费的持续时间是 - [Pre-Login] initialization=125；handshake=9010；[Login] initialization=0；authentication=0；[Post-Login] complete=5040；
2014-10-21 10:19:47,145 [25] ERROR LeaRun.DataAccess.DbHelper - Timeout 时间已到。在操作完成之前超时时间已过或服务器未响应。
2014-10-21 11:35:25,941 [52] ERROR LeaRun.DataAccess.DbHelper - Timeout 时间已到。在操作完成之前超时时间已过或服务器未响应。
2014-10-21 12:07:21,913 [11] ERROR LeaRun.DataAccess.DbHelper - 关键字 'WITH' 附近有语法错误。
关键字 'with' 附近有语法错误。如果此语句是公用表表达式或 xmlnamespaces 子句，那么前一个语句必须以分号结尾。
')' 附近有语法错误。
2014-10-21 12:07:48,940 [13] ERROR LeaRun.DataAccess.DbHelper - 关键字 'WITH' 附近有语法错误。
关键字 'with' 附近有语法错误。如果此语句是公用表表达式或 xmlnamespaces 子句，那么前一个语句必须以分号结尾。
')' 附近有语法错误。
2014-10-21 12:08:46,249 [5] ERROR LeaRun.DataAccess.DbHelper - 关键字 'WITH' 附近有语法错误。
关键字 'with' 附近有语法错误。如果此语句是公用表表达式或 xmlnamespaces 子句，那么前一个语句必须以分号结尾。
')' 附近有语法错误。
2014-10-21 12:10:22,595 [9] ERROR LeaRun.DataAccess.DbHelper - 关键字 'WITH' 附近有语法错误。
关键字 'with' 附近有语法错误。如果此语句是公用表表达式或 xmlnamespaces 子句，那么前一个语句必须以分号结尾。
')' 附近有语法错误。
2014-10-21 12:11:04,619 [10] ERROR LeaRun.DataAccess.DbHelper - 关键字 'WITH' 附近有语法错误。
关键字 'with' 附近有语法错误。如果此语句是公用表表达式或 xmlnamespaces 子句，那么前一个语句必须以分号结尾。
')' 附近有语法错误。
2014-10-21 12:11:07,898 [10] ERROR LeaRun.DataAccess.DbHelper - 关键字 'WITH' 附近有语法错误。
关键字 'with' 附近有语法错误。如果此语句是公用表表达式或 xmlnamespaces 子句，那么前一个语句必须以分号结尾。
')' 附近有语法错误。
2014-10-21 12:11:32,480 [12] ERROR LeaRun.DataAccess.DbHelper - 关键字 'WITH' 附近有语法错误。
关键字 'with' 附近有语法错误。如果此语句是公用表表达式或 xmlnamespaces 子句，那么前一个语句必须以分号结尾。
')' 附近有语法错误。
2014-10-21 13:21:44,639 [12] ERROR LeaRun.DataAccess.DbHelper - 关键字 'WITH' 附近有语法错误。
关键字 'with' 附近有语法错误。如果此语句是公用表表达式或 xmlnamespaces 子句，那么前一个语句必须以分号结尾。
')' 附近有语法错误。
