2014-12-08 08:59:35,374 [41] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@CompanyId nvarchar(4000))SELECT top 1 CompanyId,ParentId,Categ' 需要参数 @CompanyId，但未提供该参数。
2014-12-08 09:11:07,680 [12] ERROR LeaRun.DataAccess.DbHelper - 对象名  'TestTable' 无效。
2014-12-08 09:11:39,127 [29] ERROR LeaRun.DataAccess.DbHelper - 对象名  'TestTable' 无效。
2014-12-08 09:13:00,631 [7] ERROR LeaRun.DataAccess.DbHelper - 列名 'SortCode' 无效。
2014-12-08 11:28:46,535 [50] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@ObjectId"。
2014-12-08 11:31:07,163 [5] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@ObjectId"。
