2014-11-21 14:50:11,755 [6] ERROR LeaRun.DataAccess.DbHelper - 过程或函数 'PROC_verify_IPAddress' 需要参数 '@OpenId'，但未提供该参数。
2014-11-21 15:28:31,480 [8] ERROR LeaRun.DataAccess.DbHelper - error '登陆失败' 登陆失败.
2014-11-21 15:33:27,869 [9] ERROR LeaRun.DataAccess.DbHelper - error '登陆失败' 登陆失败.
2014-11-21 15:37:30,350 [7] ERROR LeaRun.DataAccess.DbHelper - error '错误提示' 登陆失败.
2014-11-21 16:27:34,747 [8] ERROR LeaRun.DataAccess.DbHelper - error '错误提示' 登陆失败.
2014-11-21 16:28:58,665 [10] ERROR LeaRun.DataAccess.DbHelper - error '错误提示' 登陆失败.
2014-11-21 16:30:26,522 [7] ERROR LeaRun.DataAccess.DbHelper - error '错误提示' 登陆失败.
2014-11-21 16:39:23,919 [6] ERROR LeaRun.DataAccess.DbHelper - error '错误提示' 登陆失败.
2014-11-21 16:41:11,340 [8] ERROR LeaRun.DataAccess.DbHelper - error '错误提示' 请先通过QQ登陆验证.
2014-11-21 17:04:19,271 [28] ERROR LeaRun.DataAccess.DbHelper - error '错误提示' 请先通过QQ登陆验证.
2014-11-21 18:29:28,087 [8] ERROR LeaRun.DataAccess.DbHelper - error '错误提示' 请先通过QQ登陆验证.
2014-11-21 18:34:24,249 [5] ERROR LoginController - 127.0.0.1;本机地址 CZ88.NET;
2014-11-21 18:34:37,941 [5] ERROR LeaRun.DataAccess.DbHelper - error '错误提示' 请先通过QQ登陆验证.
