2014-11-06 17:16:15,197 [109] ERROR LeaRun.DataAccess.DbHelper - 违反了 PRIMARY KEY 约束 'PK_BASE_SYSLOG'。不能在对象 'dbo.Base_SysLog' 中插入重复键。
语句已终止。
2014-11-06 18:12:36,413 [8] ERROR LeaRun.DataAccess.DbHelper - 列名 'ParentId' 无效。
2014-11-06 18:13:16,489 [93] ERROR LeaRun.DataAccess.DbHelper - 列名 'ParentId' 无效。
2014-11-06 18:13:25,955 [55] ERROR LeaRun.DataAccess.DbHelper - 列名 'ParentId' 无效。
2014-11-06 18:13:37,716 [105] ERROR LeaRun.DataAccess.DbHelper - 列名 'ParentId' 无效。
2014-11-06 18:13:49,835 [90] ERROR LeaRun.DataAccess.DbHelper - 列名 'ParentId' 无效。
2014-11-06 18:13:58,997 [90] ERROR LeaRun.DataAccess.DbHelper - 列名 'ParentId' 无效。
2014-11-06 18:14:02,215 [32] ERROR LeaRun.DataAccess.DbHelper - 列名 'ParentId' 无效。
2014-11-06 18:14:04,778 [92] ERROR LeaRun.DataAccess.DbHelper - 列名 'ParentId' 无效。
2014-11-06 18:14:05,548 [55] ERROR LeaRun.DataAccess.DbHelper - 列名 'ParentId' 无效。
2014-11-06 18:16:47,439 [9] ERROR LeaRun.DataAccess.DbHelper - 列名 'ParentId' 无效。
