2014-10-17 09:37:09,970 [9] ERROR LeaRun.DataAccess.DbHelper - 将截断字符串或二进制数据。
语句已终止。
2014-10-17 10:50:48,659 [41] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@FolderId nvarchar(4000),@UserId nvarchar(36))Select Count(1) F' 需要参数 @FolderId，但未提供该参数。
2014-10-17 10:53:13,912 [36] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@FolderId nvarchar(4000),@UserId nvarchar(36))Select Count(1) F' 需要参数 @FolderId，但未提供该参数。
2014-10-17 18:57:46,664 [48] ERROR LeaRun.DataAccess.DbHelper - 'FILENAME' 附近有语法错误。
'FolderName' 附近有语法错误。
2014-10-17 18:57:51,147 [45] ERROR LeaRun.DataAccess.DbHelper - 'FILENAME' 附近有语法错误。
'FolderName' 附近有语法错误。
