2014-10-29 10:32:24,660 [24] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@CodeRuleId nvarchar(4000))SELECT top 1 CodeRuleId,FullName,Cod' 需要参数 @CodeRuleId，但未提供该参数。
2014-10-29 12:40:51,059 [31] ERROR LeaRun.DataAccess.DbHelper - '1' 附近有语法错误。
2014-10-29 16:31:25,541 [9] ERROR LeaRun.DataAccess.DbHelper - 从数据类型 nvarchar 转换为 numeric 时出错。
2014-10-29 16:33:21,781 [9] ERROR LeaRun.DataAccess.DbHelper - 从数据类型 nvarchar 转换为 numeric 时出错。
2014-10-29 17:50:26,004 [15] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@BillNo"。
2014-10-29 17:51:25,397 [23] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@BillNo"。
2014-10-29 17:52:38,235 [5] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@BillNo"。
2014-10-29 17:53:09,783 [9] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@BillNo"。
2014-10-29 17:53:10,744 [8] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@BillNo"。
2014-10-29 17:53:11,054 [9] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@BillNo"。
2014-10-29 17:53:11,172 [8] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@BillNo"。
2014-10-29 17:53:11,347 [9] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@BillNo"。
2014-10-29 17:53:11,672 [7] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@BillNo"。
2014-10-29 17:53:12,022 [5] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@BillNo"。
2014-10-29 17:53:12,381 [7] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@BillNo"。
2014-10-29 17:53:12,724 [9] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@BillNo"。
2014-10-29 17:53:13,044 [7] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@BillNo"。
