2014-10-24 18:53:02,401 [25] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@CodeRuleId nvarchar(4000))SELECT top 1 CodeRuleId,FullName,Cod' 需要参数 @CodeRuleId，但未提供该参数。
2014-10-24 18:54:22,899 [13] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@ImportId nvarchar(4000))SELECT ImportDetailId,ImportId,FieldNa' 需要参数 @ImportId，但未提供该参数。
2014-10-24 18:54:35,394 [99] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@ImportId nvarchar(4000))SELECT ImportDetailId,ImportId,FieldNa' 需要参数 @ImportId，但未提供该参数。
2014-10-24 18:54:39,046 [13] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@ImportId nvarchar(4000))SELECT ImportDetailId,ImportId,FieldNa' 需要参数 @ImportId，但未提供该参数。
2014-10-24 18:54:42,143 [7] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@ImportId nvarchar(4000))SELECT ImportDetailId,ImportId,FieldNa' 需要参数 @ImportId，但未提供该参数。
