2014-12-05 15:46:08,981 [46] ERROR LeaRun.DataAccess.DbHelper - 'mp' 附近有语法错误。
字符串 'fb815f11-6457-4bf4-b600-f3dbea378ff3) ORDER BY  m.SortCode ASC ' 后的引号不完整。
2014-12-05 15:48:43,156 [9] ERROR LeaRun.DataAccess.DbHelper - 字符串 'fb815f11-6457-4bf4-b600-f3dbea378ff3) ORDER BY  m.SortCode ASC ' 后的引号不完整。
'fb815f11-6457-4bf4-b600-f3dbea378ff3) ORDER BY  m.SortCode ASC ' 附近有语法错误。
2014-12-05 15:54:01,975 [9] ERROR LeaRun.DataAccess.DbHelper - 'bp' 附近有语法错误。
2014-12-05 15:56:16,646 [7] ERROR LeaRun.DataAccess.DbHelper - 'bp' 附近有语法错误。
2014-12-05 15:59:09,280 [10] ERROR LeaRun.DataAccess.DbHelper - 列名 '' 无效。
列名 '' 无效。
2014-12-05 16:18:02,074 [17] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@CompanyId nvarchar(4000))SELECT top 1 CompanyId,ParentId,Categ' 需要参数 @CompanyId，但未提供该参数。
2014-12-05 16:22:25,550 [12] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@CompanyId nvarchar(4000))SELECT top 1 CompanyId,ParentId,Categ' 需要参数 @CompanyId，但未提供该参数。
2014-12-05 17:59:37,470 [32] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@CompanyId nvarchar(4000))SELECT top 1 CompanyId,ParentId,Categ' 需要参数 @CompanyId，但未提供该参数。
