2014-11-05 15:50:16,630 [5] ERROR LeaRun.DataAccess.DbHelper - ')' 附近有语法错误。
2014-11-05 15:50:31,575 [44] ERROR LeaRun.DataAccess.DbHelper - ')' 附近有语法错误。
2014-11-05 15:51:43,022 [82] ERROR LeaRun.DataAccess.DbHelper - ')' 附近有语法错误。
2014-11-05 15:52:45,316 [5] ERROR LeaRun.DataAccess.DbHelper - ')' 附近有语法错误。
2014-11-05 15:53:10,809 [82] ERROR LeaRun.DataAccess.DbHelper - ')' 附近有语法错误。
2014-11-05 15:54:31,531 [8] ERROR LeaRun.DataAccess.DbHelper - ')' 附近有语法错误。
2014-11-05 15:55:13,857 [10] ERROR LeaRun.DataAccess.DbHelper - '1' 附近有语法错误。
2014-11-05 15:56:17,757 [7] ERROR LeaRun.DataAccess.DbHelper - '1' 附近有语法错误。
2014-11-05 17:15:28,300 [34] ERROR LeaRun.DataAccess.DbHelper - 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: TCP Provider, error: 0 - 套接字操作尝试一个无法连接的主机。)
2014-11-05 17:15:28,301 [23] ERROR LeaRun.DataAccess.DbHelper - 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: TCP Provider, error: 0 - 套接字操作尝试一个无法连接的主机。)
2014-11-05 17:15:52,477 [37] ERROR LeaRun.DataAccess.DbHelper - 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: TCP Provider, error: 0 - 套接字操作尝试一个无法连接的主机。)
