2014-11-12 11:31:41,839 [14] ERROR LeaRun.DataAccess.DbHelper - 无法绑定由多个部分组成的标识符 "u.RealName"。
无法绑定由多个部分组成的标识符 "u.Account"。
无法绑定由多个部分组成的标识符 "u.Code"。
无法绑定由多个部分组成的标识符 "u.Spell"。
2014-11-12 11:32:49,947 [9] ERROR LeaRun.DataAccess.DbHelper - 无法绑定由多个部分组成的标识符 "u.RealName"。
无法绑定由多个部分组成的标识符 "u.Account"。
无法绑定由多个部分组成的标识符 "u.Code"。
无法绑定由多个部分组成的标识符 "u.Spell"。
2014-11-12 11:35:08,115 [15] ERROR LeaRun.DataAccess.DbHelper - 无法绑定由多个部分组成的标识符 "u.RealName"。
无法绑定由多个部分组成的标识符 "u.Account"。
无法绑定由多个部分组成的标识符 "u.Code"。
无法绑定由多个部分组成的标识符 "u.Spell"。
2014-11-12 11:37:04,422 [8] ERROR LeaRun.DataAccess.DbHelper - 无法绑定由多个部分组成的标识符 "u.RealName"。
无法绑定由多个部分组成的标识符 "u.Account"。
无法绑定由多个部分组成的标识符 "u.Code"。
无法绑定由多个部分组成的标识符 "u.Spell"。
2014-11-12 11:37:13,639 [6] ERROR LeaRun.DataAccess.DbHelper - 无法绑定由多个部分组成的标识符 "u.RealName"。
无法绑定由多个部分组成的标识符 "u.Account"。
无法绑定由多个部分组成的标识符 "u.Code"。
无法绑定由多个部分组成的标识符 "u.Spell"。
2014-11-12 11:38:06,841 [5] ERROR LeaRun.DataAccess.DbHelper - 列名 'Spell' 无效。
2014-11-12 11:39:09,369 [9] ERROR LeaRun.DataAccess.DbHelper - 列名 'Spell' 无效。
2014-11-12 11:43:53,184 [20] ERROR LeaRun.DataAccess.DbHelper - 列名 'UserIdA' 无效。
列名 'UserId' 无效。
2014-11-12 11:44:36,113 [28] ERROR LeaRun.DataAccess.DbHelper - 列名 'UserIdA' 无效。
列名 'UserId' 无效。
2014-11-12 11:46:47,402 [23] ERROR LeaRun.DataAccess.DbHelper - 列名 'UserIdA' 无效。
列名 'UserId' 无效。
2014-11-12 11:47:28,228 [18] ERROR LeaRun.DataAccess.DbHelper - 列名 'UserIdA' 无效。
列名 'UserId' 无效。
